/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedOnboardedRouteImport } from './routes/_protected/_onboarded'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminSsoRouteImport } from './routes/_protected/admin/sso'
import { Route as ProtectedAdminScimRouteImport } from './routes/_protected/admin/scim'
import { Route as ProtectedAcceptInvitationInvitationIdRouteImport } from './routes/_protected/accept-invitation.$invitationId'
import { Route as ProtectedOnboardedOrgRouteImport } from './routes/_protected/_onboarded/org'
import { Route as ProtectedOnboardedDashboardRouteImport } from './routes/_protected/_onboarded/dashboard'
import { Route as ProtectedOnboardedOrgIndexRouteImport } from './routes/_protected/_onboarded/org/index'
import { Route as ProtectedAdminUserUserIdRouteImport } from './routes/_protected/admin/user.$userId'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug'
import { Route as ProtectedOnboardedOrgWorkspacesRouteImport } from './routes/_protected/_onboarded/org/workspaces'
import { Route as ProtectedOnboardedOrgTeamsRouteImport } from './routes/_protected/_onboarded/org/teams'
import { Route as ProtectedOnboardedOrgSettingsRouteImport } from './routes/_protected/_onboarded/org/settings'
import { Route as ProtectedOnboardedOrgMembersRouteImport } from './routes/_protected/_onboarded/org/members'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugIndexRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug/index'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug/settings'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug/relationships'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugElementsRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug/elements'
import { Route as ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRouteImport } from './routes/_protected/_onboarded/workspace/$workspaceSlug/diagrams'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardedRoute = ProtectedOnboardedRouteImport.update({
  id: '/_onboarded',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminSsoRoute = ProtectedAdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminScimRoute = ProtectedAdminScimRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAcceptInvitationInvitationIdRoute =
  ProtectedAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOnboardedOrgRoute = ProtectedOnboardedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => ProtectedOnboardedRoute,
} as any)
const ProtectedOnboardedDashboardRoute =
  ProtectedOnboardedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedOnboardedRoute,
  } as any)
const ProtectedOnboardedOrgIndexRoute =
  ProtectedOnboardedOrgIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOnboardedOrgRoute,
  } as any)
const ProtectedAdminUserUserIdRoute =
  ProtectedAdminUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugRouteImport.update({
    id: '/workspace/$workspaceSlug',
    path: '/workspace/$workspaceSlug',
    getParentRoute: () => ProtectedOnboardedRoute,
  } as any)
const ProtectedOnboardedOrgWorkspacesRoute =
  ProtectedOnboardedOrgWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => ProtectedOnboardedOrgRoute,
  } as any)
const ProtectedOnboardedOrgTeamsRoute =
  ProtectedOnboardedOrgTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => ProtectedOnboardedOrgRoute,
  } as any)
const ProtectedOnboardedOrgSettingsRoute =
  ProtectedOnboardedOrgSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOnboardedOrgRoute,
  } as any)
const ProtectedOnboardedOrgMembersRoute =
  ProtectedOnboardedOrgMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOnboardedOrgRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOnboardedWorkspaceWorkspaceSlugRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOnboardedWorkspaceWorkspaceSlugRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => ProtectedOnboardedWorkspaceWorkspaceSlugRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugElementsRouteImport.update({
    id: '/elements',
    path: '/elements',
    getParentRoute: () => ProtectedOnboardedWorkspaceWorkspaceSlugRoute,
  } as any)
const ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute =
  ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRouteImport.update({
    id: '/diagrams',
    path: '/diagrams',
    getParentRoute: () => ProtectedOnboardedWorkspaceWorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/settings': typeof ProtectedSettingsRoute
  '/dashboard': typeof ProtectedOnboardedDashboardRoute
  '/org': typeof ProtectedOnboardedOrgRouteWithChildren
  '/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/admin/scim': typeof ProtectedAdminScimRoute
  '/admin/sso': typeof ProtectedAdminSsoRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/org/members': typeof ProtectedOnboardedOrgMembersRoute
  '/org/settings': typeof ProtectedOnboardedOrgSettingsRoute
  '/org/teams': typeof ProtectedOnboardedOrgTeamsRoute
  '/org/workspaces': typeof ProtectedOnboardedOrgWorkspacesRoute
  '/workspace/$workspaceSlug': typeof ProtectedOnboardedWorkspaceWorkspaceSlugRouteWithChildren
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute
  '/org/': typeof ProtectedOnboardedOrgIndexRoute
  '/workspace/$workspaceSlug/diagrams': typeof ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute
  '/workspace/$workspaceSlug/elements': typeof ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute
  '/workspace/$workspaceSlug/relationships': typeof ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute
  '/workspace/$workspaceSlug/settings': typeof ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute
  '/workspace/$workspaceSlug/': typeof ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/settings': typeof ProtectedSettingsRoute
  '/dashboard': typeof ProtectedOnboardedDashboardRoute
  '/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/admin/scim': typeof ProtectedAdminScimRoute
  '/admin/sso': typeof ProtectedAdminSsoRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/org/members': typeof ProtectedOnboardedOrgMembersRoute
  '/org/settings': typeof ProtectedOnboardedOrgSettingsRoute
  '/org/teams': typeof ProtectedOnboardedOrgTeamsRoute
  '/org/workspaces': typeof ProtectedOnboardedOrgWorkspacesRoute
  '/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute
  '/org': typeof ProtectedOnboardedOrgIndexRoute
  '/workspace/$workspaceSlug/diagrams': typeof ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute
  '/workspace/$workspaceSlug/elements': typeof ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute
  '/workspace/$workspaceSlug/relationships': typeof ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute
  '/workspace/$workspaceSlug/settings': typeof ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute
  '/workspace/$workspaceSlug': typeof ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/_onboarded': typeof ProtectedOnboardedRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/_onboarded/dashboard': typeof ProtectedOnboardedDashboardRoute
  '/_protected/_onboarded/org': typeof ProtectedOnboardedOrgRouteWithChildren
  '/_protected/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/_protected/admin/scim': typeof ProtectedAdminScimRoute
  '/_protected/admin/sso': typeof ProtectedAdminSsoRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/_onboarded/org/members': typeof ProtectedOnboardedOrgMembersRoute
  '/_protected/_onboarded/org/settings': typeof ProtectedOnboardedOrgSettingsRoute
  '/_protected/_onboarded/org/teams': typeof ProtectedOnboardedOrgTeamsRoute
  '/_protected/_onboarded/org/workspaces': typeof ProtectedOnboardedOrgWorkspacesRoute
  '/_protected/_onboarded/workspace/$workspaceSlug': typeof ProtectedOnboardedWorkspaceWorkspaceSlugRouteWithChildren
  '/_protected/admin/user/$userId': typeof ProtectedAdminUserUserIdRoute
  '/_protected/_onboarded/org/': typeof ProtectedOnboardedOrgIndexRoute
  '/_protected/_onboarded/workspace/$workspaceSlug/diagrams': typeof ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute
  '/_protected/_onboarded/workspace/$workspaceSlug/elements': typeof ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute
  '/_protected/_onboarded/workspace/$workspaceSlug/relationships': typeof ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute
  '/_protected/_onboarded/workspace/$workspaceSlug/settings': typeof ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute
  '/_protected/_onboarded/workspace/$workspaceSlug/': typeof ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/admin'
    | '/onboarding'
    | '/settings'
    | '/dashboard'
    | '/org'
    | '/accept-invitation/$invitationId'
    | '/admin/scim'
    | '/admin/sso'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin/'
    | '/org/members'
    | '/org/settings'
    | '/org/teams'
    | '/org/workspaces'
    | '/workspace/$workspaceSlug'
    | '/admin/user/$userId'
    | '/org/'
    | '/workspace/$workspaceSlug/diagrams'
    | '/workspace/$workspaceSlug/elements'
    | '/workspace/$workspaceSlug/relationships'
    | '/workspace/$workspaceSlug/settings'
    | '/workspace/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/onboarding'
    | '/settings'
    | '/dashboard'
    | '/accept-invitation/$invitationId'
    | '/admin/scim'
    | '/admin/sso'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin'
    | '/org/members'
    | '/org/settings'
    | '/org/teams'
    | '/org/workspaces'
    | '/admin/user/$userId'
    | '/org'
    | '/workspace/$workspaceSlug/diagrams'
    | '/workspace/$workspaceSlug/elements'
    | '/workspace/$workspaceSlug/relationships'
    | '/workspace/$workspaceSlug/settings'
    | '/workspace/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/_protected/_onboarded'
    | '/_protected/admin'
    | '/_protected/onboarding'
    | '/_protected/settings'
    | '/_protected/_onboarded/dashboard'
    | '/_protected/_onboarded/org'
    | '/_protected/accept-invitation/$invitationId'
    | '/_protected/admin/scim'
    | '/_protected/admin/sso'
    | '/_protected/admin/users'
    | '/api/auth/$'
    | '/_protected/admin/'
    | '/_protected/_onboarded/org/members'
    | '/_protected/_onboarded/org/settings'
    | '/_protected/_onboarded/org/teams'
    | '/_protected/_onboarded/org/workspaces'
    | '/_protected/_onboarded/workspace/$workspaceSlug'
    | '/_protected/admin/user/$userId'
    | '/_protected/_onboarded/org/'
    | '/_protected/_onboarded/workspace/$workspaceSlug/diagrams'
    | '/_protected/_onboarded/workspace/$workspaceSlug/elements'
    | '/_protected/_onboarded/workspace/$workspaceSlug/relationships'
    | '/_protected/_onboarded/workspace/$workspaceSlug/settings'
    | '/_protected/_onboarded/workspace/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_onboarded': {
      id: '/_protected/_onboarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedOnboardedRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/sso': {
      id: '/_protected/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof ProtectedAdminSsoRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/scim': {
      id: '/_protected/admin/scim'
      path: '/scim'
      fullPath: '/admin/scim'
      preLoaderRoute: typeof ProtectedAdminScimRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/accept-invitation/$invitationId': {
      id: '/_protected/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof ProtectedAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_onboarded/org': {
      id: '/_protected/_onboarded/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof ProtectedOnboardedOrgRouteImport
      parentRoute: typeof ProtectedOnboardedRoute
    }
    '/_protected/_onboarded/dashboard': {
      id: '/_protected/_onboarded/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedOnboardedDashboardRouteImport
      parentRoute: typeof ProtectedOnboardedRoute
    }
    '/_protected/_onboarded/org/': {
      id: '/_protected/_onboarded/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof ProtectedOnboardedOrgIndexRouteImport
      parentRoute: typeof ProtectedOnboardedOrgRoute
    }
    '/_protected/admin/user/$userId': {
      id: '/_protected/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof ProtectedAdminUserUserIdRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug'
      path: '/workspace/$workspaceSlug'
      fullPath: '/workspace/$workspaceSlug'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRouteImport
      parentRoute: typeof ProtectedOnboardedRoute
    }
    '/_protected/_onboarded/org/workspaces': {
      id: '/_protected/_onboarded/org/workspaces'
      path: '/workspaces'
      fullPath: '/org/workspaces'
      preLoaderRoute: typeof ProtectedOnboardedOrgWorkspacesRouteImport
      parentRoute: typeof ProtectedOnboardedOrgRoute
    }
    '/_protected/_onboarded/org/teams': {
      id: '/_protected/_onboarded/org/teams'
      path: '/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof ProtectedOnboardedOrgTeamsRouteImport
      parentRoute: typeof ProtectedOnboardedOrgRoute
    }
    '/_protected/_onboarded/org/settings': {
      id: '/_protected/_onboarded/org/settings'
      path: '/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof ProtectedOnboardedOrgSettingsRouteImport
      parentRoute: typeof ProtectedOnboardedOrgRoute
    }
    '/_protected/_onboarded/org/members': {
      id: '/_protected/_onboarded/org/members'
      path: '/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof ProtectedOnboardedOrgMembersRouteImport
      parentRoute: typeof ProtectedOnboardedOrgRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug/': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug/'
      path: '/'
      fullPath: '/workspace/$workspaceSlug/'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugIndexRouteImport
      parentRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug/settings': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceSlug/settings'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRouteImport
      parentRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug/relationships': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug/relationships'
      path: '/relationships'
      fullPath: '/workspace/$workspaceSlug/relationships'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRouteImport
      parentRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug/elements': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug/elements'
      path: '/elements'
      fullPath: '/workspace/$workspaceSlug/elements'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugElementsRouteImport
      parentRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRoute
    }
    '/_protected/_onboarded/workspace/$workspaceSlug/diagrams': {
      id: '/_protected/_onboarded/workspace/$workspaceSlug/diagrams'
      path: '/diagrams'
      fullPath: '/workspace/$workspaceSlug/diagrams'
      preLoaderRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRouteImport
      parentRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRoute
    }
  }
}

interface ProtectedOnboardedOrgRouteChildren {
  ProtectedOnboardedOrgMembersRoute: typeof ProtectedOnboardedOrgMembersRoute
  ProtectedOnboardedOrgSettingsRoute: typeof ProtectedOnboardedOrgSettingsRoute
  ProtectedOnboardedOrgTeamsRoute: typeof ProtectedOnboardedOrgTeamsRoute
  ProtectedOnboardedOrgWorkspacesRoute: typeof ProtectedOnboardedOrgWorkspacesRoute
  ProtectedOnboardedOrgIndexRoute: typeof ProtectedOnboardedOrgIndexRoute
}

const ProtectedOnboardedOrgRouteChildren: ProtectedOnboardedOrgRouteChildren = {
  ProtectedOnboardedOrgMembersRoute: ProtectedOnboardedOrgMembersRoute,
  ProtectedOnboardedOrgSettingsRoute: ProtectedOnboardedOrgSettingsRoute,
  ProtectedOnboardedOrgTeamsRoute: ProtectedOnboardedOrgTeamsRoute,
  ProtectedOnboardedOrgWorkspacesRoute: ProtectedOnboardedOrgWorkspacesRoute,
  ProtectedOnboardedOrgIndexRoute: ProtectedOnboardedOrgIndexRoute,
}

const ProtectedOnboardedOrgRouteWithChildren =
  ProtectedOnboardedOrgRoute._addFileChildren(
    ProtectedOnboardedOrgRouteChildren,
  )

interface ProtectedOnboardedWorkspaceWorkspaceSlugRouteChildren {
  ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute
  ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute
  ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute
  ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute
  ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute
}

const ProtectedOnboardedWorkspaceWorkspaceSlugRouteChildren: ProtectedOnboardedWorkspaceWorkspaceSlugRouteChildren =
  {
    ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute:
      ProtectedOnboardedWorkspaceWorkspaceSlugDiagramsRoute,
    ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute:
      ProtectedOnboardedWorkspaceWorkspaceSlugElementsRoute,
    ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute:
      ProtectedOnboardedWorkspaceWorkspaceSlugRelationshipsRoute,
    ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute:
      ProtectedOnboardedWorkspaceWorkspaceSlugSettingsRoute,
    ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute:
      ProtectedOnboardedWorkspaceWorkspaceSlugIndexRoute,
  }

const ProtectedOnboardedWorkspaceWorkspaceSlugRouteWithChildren =
  ProtectedOnboardedWorkspaceWorkspaceSlugRoute._addFileChildren(
    ProtectedOnboardedWorkspaceWorkspaceSlugRouteChildren,
  )

interface ProtectedOnboardedRouteChildren {
  ProtectedOnboardedDashboardRoute: typeof ProtectedOnboardedDashboardRoute
  ProtectedOnboardedOrgRoute: typeof ProtectedOnboardedOrgRouteWithChildren
  ProtectedOnboardedWorkspaceWorkspaceSlugRoute: typeof ProtectedOnboardedWorkspaceWorkspaceSlugRouteWithChildren
}

const ProtectedOnboardedRouteChildren: ProtectedOnboardedRouteChildren = {
  ProtectedOnboardedDashboardRoute: ProtectedOnboardedDashboardRoute,
  ProtectedOnboardedOrgRoute: ProtectedOnboardedOrgRouteWithChildren,
  ProtectedOnboardedWorkspaceWorkspaceSlugRoute:
    ProtectedOnboardedWorkspaceWorkspaceSlugRouteWithChildren,
}

const ProtectedOnboardedRouteWithChildren =
  ProtectedOnboardedRoute._addFileChildren(ProtectedOnboardedRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminScimRoute: typeof ProtectedAdminScimRoute
  ProtectedAdminSsoRoute: typeof ProtectedAdminSsoRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminUserUserIdRoute: typeof ProtectedAdminUserUserIdRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminScimRoute: ProtectedAdminScimRoute,
  ProtectedAdminSsoRoute: ProtectedAdminSsoRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminUserUserIdRoute: ProtectedAdminUserUserIdRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedOnboardedRoute: typeof ProtectedOnboardedRouteWithChildren
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedAcceptInvitationInvitationIdRoute: typeof ProtectedAcceptInvitationInvitationIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOnboardedRoute: ProtectedOnboardedRouteWithChildren,
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedAcceptInvitationInvitationIdRoute:
    ProtectedAcceptInvitationInvitationIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
